- id: ddns_update
  alias: 'Update 1984.is A record'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: shell_command.ddns_renew

- id: zack_leaving
  alias: "Zack - Leaving for work"
  trigger:
    platform: state
    entity_id: device_tracker.zacks_pixel2xl
    from: 'home'
    to: 'not_home'
  condition:
    - condition: time
      after: '07:15:00'
      before: '08:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: notify.slack
    data_template:
      message: >
        Zack is heading to work.
      target: "#carpooling"

- id: nest_alert
  alias: "Nest Temperature Alert"
  trigger:
    platform: state
    entity_id: device_tracker.zacks_pixel2xl
    from: 'home'
    to: 'not_home'
  action:
    service: notify.gmail_text
    data:
      title: 'Low temperature alert'
      message: 'Low temperature at Nest location!!'
