- id: ddns_update
  alias: 'Update 1984.is A record'
  trigger:
    platform: time
    at: '00:00:00'
    #seconds: '/5' #for testing every 5 seconds
  action:
    service: shell_command.ddns_renew
    
- id: zack_leaving
  alias: "Zack - Leaving for work"
  trigger:
    platform: state
    entity_id: device_tracker.zacks_pixel2xl
    # Optional
    from: 'home'
    # Optional
    to: 'not_home'
    # If given, will trigger when state has been the to state for X time.
  # for:
    # hours: 1
    # minutes: 10
    # seconds: 5
  condition:
    - condition: time
      after: '00:00:00'
      before: '23:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
  action:
    service: notify.slack
    data_template:
      message: >
        Zack is heading to work.
      target: "#carpooling"
