homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.713260
  longitude: -72.307466
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 900
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

http:
  #base_url: https://benn.is:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# Text to speech
tts:

# Cloud
cloud:

# Shell Commands
shell_command:
  ddns_renew: !secret ddns_renew
  
# Device tracking
device_tracker:
  - platform: nmap_tracker
    hosts: 10.200.50.51
    home_interval: 1

# Notifications
notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#carpool'

  - name: gmail_text
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_user
    encryption: starttls
    username: !secret gmail_user
    password: !secret gmail_pass
    recipient:
      - 5163195709@vtext.com
    sender_name: Nest Alert

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
